{% set name = "colordiff" %}
{% set version = "1.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.colordiff.org/archive/{{ name }}-{{ version }}.tar.gz
  sha256: e3b2017beeb9f619ebc3b15392f22810c882d1b657aab189623cffef351d7bcd

build:
  number: 0
  noarch: generic

requirements:
  build:
    - make
  run:
    - perl

test:
  requires:
    - perl
  commands:
    - colordiff --version

about:
  home: https://www.colordiff.org/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: Colordiff is a wrapper for diff and produces the same output but with pretty syntax highlighting.
  description: |
    Colordiff is a wrapper for diff and produces the same output as diff but
    with coloured syntax highlighting at the command line to improve
    readability. The output is similar to how a diff-generated patch might
    appear in Vim or Emacs with the appropriate syntax highlighting options
    enabled.
  doc_url: https://www.colordiff.org/colordiff.html
  dev_url: https://github.com/daveewart/colordiff

extra:
  recipe-maintainers:
    - matthiasdiener
